name: Autofill PR Description

on:
  workflow_dispatch:

  pull_request:
    branches:
      - main

permissions:
  pull-requests: write
  contents: read

jobs:
  openai-pr-description:
    runs-on: ubuntu-22.04
    if: ${{ !startsWith(github.actor, 'dependabot') }}
    steps:
      - uses: platisd/openai-pr-description@v1.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          openai_api_key: ${{ secrets.OPEN_AI_PR_DESCRIPTION_API_KEY }}
          overwrite_description: true
          openai_model: gpt-4o
          temperature: 0.2
          completion_prompt: |
            Summarize the changes of this PR in no more than 3 sentences. In a structured way, list the changes of this PR.
